### ISSUE TITLE
Demo doesnt works

### ISSUE THREAD

**Issue by Evil85** [xoco70/laravel-tournaments#36]
I tried to check your demo site here : https://demo.kendozone.com/laravel-tournaments

Then I gave this error : 

`
ErrorException (E_ERROR)
Undefined offset: 0 (View: /home/forge/demo.kendozone.com/vendor/xoco70/laravel-tournaments/resources/views/partials/tree/singleElimination.blade.php) (View: /home/forge/demo.kendozone.com/vendor/xoco70/laravel-tournaments/resources/views/partials/tree/singleElimination.blade.php)
`

**Comment by xoco70** [comment]
oopps ! Will check it tonight !

**Comment by xoco70** [comment]
fixed ! Please give it a try !

**Comment by rzdev** [comment]
Demo does not work.

Also, I've tried to get the demo running on my local computer, followed the instructions and then opened up `http://localhost/tournament/public/laravel-tournaments` but the response is 404. Are there anything that needs to be done?
