### ISSUE TITLE
General error: 1005 Can't create table `homg`.`tournament`

### ISSUE THREAD

**Issue by NoelBradford** [xoco70/laravel-tournaments#37]
Getting the above error when migrating
<img width="1280" alt="Screenshot 2019-05-10 at 16 18 27" src="https://user-images.githubusercontent.com/8930657/57538001-58b68000-733f-11e9-9686-642eb39367a3.png">

**Comment by xoco70** [comment]
Tx for reporting, I am working on it

**Comment by xoco70** [comment]
Bug is due to that Laravel 5.8 has changed default userId from integer to bigInteger. https://laraveldaily.com/be-careful-laravel-5-8-added-bigincrements-as-defaults/ 
Try it again, it should work, feel free to reopen the issue if issue is not fixed
