### ISSUE TITLE
Help! Having trouble in installing the package in laravel 5.4 and 5.3

### ISSUE THREAD

**Issue by kristernavi** [xoco70/laravel-tournaments#4]
as what the title says. im getting this error

![screen shot 2017-08-02 at 5 35 59 pm](https://user-images.githubusercontent.com/12774978/28867599-33620736-77a9-11e7-983b-4c9e6f460e89.png)

**Comment by xoco70** [comment]
You're right. I'll let you know when it's done!

**Comment by xoco70** [comment]
Now it should Work! Give it a try. I tagged it with version

**Comment by xoco70** [comment]
Now it should be ok in version 0.11.16

**Comment by AyronRangel** [comment]
xoco70, i have the same problem!!! What is the solution??

**Comment by xoco70** [comment]
Can you please give me your Laravel version and your laravel-tournament version ?

**Comment by AyronRangel** [comment]
Laravel version 5.5 and the tournament version 0.13.


I tried to install on my computer, in the last step "http://yourdomain.com/laravel-tournament" i dont know my domain.... i didn't configure the host in my C:\


hostingdomains.com&nbsp;-&nbspThis website is for sale!&nbsp;-&nbsphostingdomains Resources and Information.<http://yourdomain.com/laravel-tournament>
yourdomain.com
This website is for sale! hostingdomains.com is your first and best source for all of the information you’re looking for. From general topics to more of what you would expect to find here, hostingdomains.com has it all. We hope you find what you are searching for!




________________________________
De: Julien <notifications@github.com>
Enviado: terça-feira, 6 de fevereiro de 2018 03:38
Para: xoco70/laravel-tournaments
Cc: Ayron Rangel de Todos os Santos; Comment
Assunto: Re: [xoco70/laravel-tournaments] Help! Having trouble in installing the package in laravel 5.4 and 5.3 (#4)


Can you please give me your Laravel version and your laravel-tournament version ?

**Comment by xoco70** [comment]
What is your root URL ? How do you access your site before installing plugin ?

**Comment by AyronRangel** [comment]
Let me see! I dont know kkkkkk

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
