### ISSUE TITLE
Need For Laravel 7

### ISSUE THREAD

**Issue by rashed50702** [xoco70/laravel-tournaments#42]
I need to use it for the Laravel 7 version. Would you please upgrade the version! 
Now, during installation, I am getting this error-
`    - Installation request for xoco70/laravel-tournaments ^0.16.0 -> satisfiable by xoco70/laravel-tournaments[0.16].`

**Comment by xoco70** [comment]
It's been a while I don't check it, let me see what I can do !

**Comment by xoco70** [comment]
I updated the plugin, and made a demo repository using Laravel 7: https://github.com/xoco70/laravel-tournaments-demo
